# Site settings
encoding: utf-8

title: Polymer Redux
heading: Polymer ❤ Redux
tagline: Polymer bindings for Redux.

baseurl: "/polymer-redux"
url: "http://tur-nr.github.io"

# Build settings
markdown: kramdown

gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - bower_components
  - node_modules